name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build Windows
      run: GO111MODULE=auto GOOS=windows GOARCH=amd64 go build -o build/tsw2-charmapper-win64.exe ./src/de.vad_systems.tsw2.zza
    - name: Build Linux
      run: GO111MODULE=auto GOOS=linux GOARCH=amd64 go build -o build/tsw2-charmapper-linux64 ./src/de.vad_systems.tsw2.zza
    - name: Build MacOS
      run: GO111MODULE=auto GOOS=darwin GOARCH=amd64 go build -o build/tsw2-charmapper-darwin64.bin ./src/de.vad_systems.tsw2.zza
    - name: Upload artifact Windows
      uses: actions/upload-artifact@v3
      with:
        name: tsw2-charmapper-win64.exe
        path: build/tsw2-charmapper-win64.exe
    - name: Upload artifact Linux
      uses: actions/upload-artifact@v3
      with:
        name: tsw2-charmapper-linux64
        path: build/tsw2-charmapper-linux64
    - name: Upload artifact MacOS
      uses: actions/upload-artifact@v3
      with:
        name: tsw2-charmapper-darwin64.bin
        path: build/tsw2-charmapper-darwin64.bin
