name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build ./src/de.vad_systems.tsw2.zza -o build/tsw2-charmapper-win64.exe
    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 go build ./src/de.vad_systems.tsw2.zza -o build/tsw2-charmapper-linux64
    - name: Build MacOS
      run: GOOS=darwin GOARCH=amd64 go build ./src/de.vad_systems.tsw2.zza -o build/tsw2-charmapper-darwin64.bin
